### ISSUE TITLE
OSError: broken data stream when reading image file

### ISSUE THREAD

**Issue by Meorge** [Meorge/objection_engine#1]
Appears to have happened when trying to render Adrian's sprites?

```
Traceback (most recent call last):
  File "/Users/malcolmanderson/Documents/Repositories/objection_engine/examples/v4/example_scene.py", line 43, in <module>
    render_comment_list(comments)
  File "/Users/malcolmanderson/Documents/Repositories/objection_engine/objection_engine/v4/make_movie.py", line 103, in render_comment_list
    builder.render(comment_list, music_code, assigned_characters, adult_mode)
  File "/Users/malcolmanderson/Documents/Repositories/objection_engine/objection_engine/v4/ace_attorney_scene.py", line 1463, in render
    director.render_movie(volume)
  File "/Users/malcolmanderson/Documents/Repositories/objection_engine/objection_engine/v4/MovieKit.py", line 420, in render_movie
    self.update(1 / self.fps)
  File "/Users/malcolmanderson/Documents/Repositories/objection_engine/objection_engine/v4/ace_attorney_scene.py", line 603, in update
    self.witness.set_filepath(path)
  File "/Users/malcolmanderson/Documents/Repositories/objection_engine/objection_engine/v4/MovieKit.py", line 217, in set_filepath
    my_img.convert('RGBA'),
  File "/Users/malcolmanderson/Library/Caches/pypoetry/virtualenvs/objection-engine-Acfxk5DR-py3.10/lib/python3.10/site-packages/PIL/Image.py", line 921, in convert
    self.load()
  File "/Users/malcolmanderson/Library/Caches/pypoetry/virtualenvs/objection-engine-Acfxk5DR-py3.10/lib/python3.10/site-packages/PIL/ImageFile.py", line 279, in load
    raise_oserror(err_code)
  File "/Users/malcolmanderson/Library/Caches/pypoetry/virtualenvs/objection-engine-Acfxk5DR-py3.10/lib/python3.10/site-packages/PIL/ImageFile.py", line 71, in raise_oserror
    raise OSError(message + " when reading image file")
OSError: broken data stream when reading image file
```

**Comment by Meorge** [comment]
Fixed by adding
```py
ImageFile.LOAD_TRUNCATED_IMAGES = True
```
At least, until this brings up other issues.

This only appeared to be an issue with
```
adrian-book-talk.gif
adrian-thinking-idle.gif
adrian-thinking-talk.gif
```
